config/urls.py
from django.contrib import admin
from django.urls import path, include

# メディアファイル配信の処理
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("oneall.urls")),
    path("accounts/", include("allauth.urls")),
    path("news/", include("news.urls")),
    path("textbook/", include("textbook.urls")),
    # path("content/", include("content.urls")),
    path("sales/", include("sales.urls")),
    # path("qa/", include("qa.urls")),
    # path("chat/", include("chat.urls")),
    
    path("users/", include("users.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oneall/urls.py
from django.urls import path
from . import views

app_name = "oneall"
urlpatterns = [
    path("", views.index, name="index"),
]

qa/urls.py
from django.urls import path
from . import views

app_name = "qa"
urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("question_good/<int:pk>/", views.question_good, name="question_good"),
    path("answer_good/<int:q_id>/<int:a_id>/", views.answer_good, name="answer_good"),
]

textbook/urls.py
from django.urls import path
from . import views

app_name = "textbook"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("add_major_category/", views.add_major_category, name="add_major_category"),
    path("add_minor_category/", views.add_minor_category, name="add_minor_category"),
]

textbook/models.py
from django.db import models
from django.conf import settings

from django.utils import timezone

class MajorCategory(models.Model):
    name    = models.CharField(verbose_name="大カテゴリ名", max_length=20, unique=True)

    order   = models.IntegerField(verbose_name="順番", unique=True)

    def __str__(self):
        return self.name

    def str_id(self):
        return str(self.id)

class MinorCategory(models.Model):
    name    = models.CharField(verbose_name="小カテゴリ名", max_length=20)
    order   = models.IntegerField(verbose_name="順番")

    parent  = models.ForeignKey(MajorCategory, verbose_name="大カテゴリ", on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def str_id(self):
        return str(self.id)

class Textbook(models.Model):
    dt              = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.SET_NULL, null=True, blank=True)

    title           = models.CharField(verbose_name="タイトル", max_length=100)
    thumbnail       = models.ImageField(verbose_name="サムネイル画像", upload_to="textbook/thubnail/", null=True, blank=True)
    thumbnail_url   = models.URLField(verbose_name="Youtubeのサムネイル", null=True, blank=True)
    file_content    = models.FileField(verbose_name="ファイル", upload_to="textbook/movie/", null=True, blank=True)
    is_youtube      = models.BooleanField(verbose_name="Youtubeか", default=False)
    youtube_url     = models.URLField(verbose_name="YoutubeURL", null=True, blank=True)
    order           = models.IntegerField(verbose_name="表示の順番", null=True, blank=True)

    is_top          = models.BooleanField(verbose_name="トップ表示", default=False)
    top_order       = models.IntegerField(verbose_name="トップ表示の順番", null=True, blank=True)
    explanation     = models.CharField(verbose_name="説明文", max_length=5000, null=True, blank=True)

    major_category  = models.ForeignKey(MajorCategory, verbose_name="大カテゴリ", on_delete=models.PROTECT)
    minor_category  = models.ForeignKey(MinorCategory, verbose_name="小カテゴリ", on_delete=models.PROTECT)

    def __str__(self):
        return self.title

textbook/forms.py
from django import forms
from .models import Textbook, MajorCategory, MinorCategory

from django.core.exceptions import ValidationError

class TextbookForm(forms.ModelForm):

    class Meta:
        model   = Textbook
        fields  = ["user", "title", "thumbnail", "thumbnail_url", "file_content", "major_category", "minor_category", "is_youtube", "youtube_url", "order", "is_top", "top_order", "explanation"]
    
    def clean(self):
        data    = self.cleaned_data
        
        if data["is_youtube"]:
            if not data["youtube_url"]:
                raise ValidationError("YoutubeのURLを入力してください")
        else:
            if not data["file_content"]:
                raise ValidationError("ファイルをアップロードしてください")


class MajorCategoryForm(forms.ModelForm):

    class Meta:
        model   = MajorCategory
        fields  = ["name", "order"]

class MinorCategoryForm(forms.ModelForm):

    class Meta:
        model   = MinorCategory
        fields  = ["parent","name", "order"]


class MajorCategorySearchForm(forms.ModelForm):

    class Meta:
        model   = Textbook
        fields  = ["major_category"]


class MinorCategorySearchForm(forms.ModelForm):

    class Meta:
        model   = Textbook
        fields  = ["minor_category"]    


class TextbookAdminForm(forms.ModelForm):

    class Meta:
        model   = Textbook
        fields  = ["id", "order", "dt", "is_top", "top_order", "title", "major_category", "minor_category", "explanation"]

        widgets = {
            "explanation": forms.Textarea(attrs={ "maxlength":str(Textbook.explanation.field.max_length) })
        }
        

textbook/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from django.db.models import Q
from django.core.paginator import Paginator

from .models import MajorCategory, MinorCategory, Textbook
from .forms import TextbookForm, MajorCategoryForm, MinorCategoryForm
from .forms import MajorCategorySearchForm, MinorCategorySearchForm

from . import scraping

from django.contrib import messages

from django.http.response import JsonResponse
from django.template.loader import render_to_string


class IndexView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {}
        query   = Q()
        
        form    = MajorCategorySearchForm(request.GET)        
        if form.is_valid():
            cleaned = form.clean()
            query   &= Q(major_category=cleaned["major_category"].id)
        
        form    = MinorCategorySearchForm(request.GET)
        if form.is_valid():
            cleaned = form.clean()
            query   &= Q(minor_category=cleaned["minor_category"].id)
        
        context["textbooks"]    = Textbook.objects.filter(query).order_by("top_order", "order", "-dt")
                
        context["major_categories"] = MajorCategory.objects.all().order_by("order")
        context["minor_categories"] = MinorCategory.objects.all().order_by("order")

        return render(request, "textbook/index.html", context)

    def post(self, request, *args, **kwargs):
        copied              = request.POST.copy()
        copied["user"]      = request.user.id

        print(copied)

        if "is_youtube" in copied:
            copied["thumbnail_url"] = scraping.youtube_thumbnail(copied)

        form                = TextbookForm(copied, request.FILES)
        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return redirect("textbook:index")
        
        form.save()

        return redirect("textbook:index")


index = IndexView.as_view()


class AddTextbookView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        data    = { "error": True }

        # form    = MajorCategoryForm(request.GET)

        # if not form.is_valid():
        #     print(form.errors)
        #     return JsonResponse(data)
        
        # cleaned     = form.clean()
        
        context     = {}
        context["minor_categories"] = MinorCategory.objects.filter(parent=request.GET["major_category"])

        data["error"]   = False
        data["content"] = render_to_string("textbook/minor_category.html", context, request)

        return JsonResponse(data)


add = AddTextbookView.as_view()


class AddMajorCategoryView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):

        major_categories    = MajorCategory.objects.all()
        copied              = request.POST.copy()

        form    = MajorCategoryForm(copied)
        if not form.is_valid():
            print(form.errors)
            
            values  = form.errors.get_json_data().values()
            for value in values:
                for v in value:
                    messages.error(request, v["message"])
            
            return redirect("textbook:index")
        
        print("バリデーションOK")
        form.save()

        return redirect("textbook:index")


add_major_category = AddMajorCategoryView.as_view()


class AddMinorCategoryView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):

        minor_categories    = MinorCategory.objects.all()
        copied              = request.POST.copy()

        form    = MinorCategoryForm(copied)
        if not form.is_valid():
            print(form.errors)
            
            # values  = form.errors.get_json_data().values()
            # for value in values:
            #     for v in value:
            #         messages.error(request, v["message"])
            
            return redirect("textbook:index")
        
        print("バリデーションOK")
        form.save()

        return redirect("textbook:index")



add_minor_category = AddMinorCategoryView.as_view()

templates/textbook/index.html
{% extends "oneall/base.html" %}
{% load static %}
{% load url_change %}


{% block extra_head %}
<title>教材 －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'textbook/css/index.css' %}">
<link rel="stylesheet" href="{% static 'textbook/css/index-sp.css' %}">
<link rel="stylesheet" href="{% static 'textbook/css/textbook_form.css' %}">
<link rel="stylesheet" href="{% static 'oneall/css/modal_diagram.css' %}">

<script src="{% static 'textbook/js/index.js' %}"></script>
<script src="{% static 'textbook/js/textbook_form.js' %}"></script>
{% endblock %}


{% block main %}
<h1>TEXTBOOK</h1>
<section>
    <div class="nav_link">
        <a href="{% url 'oneall:index' %}" class="to_upper_layer">ホーム</a>
        <span style="padding: 0 0.25rem">></span>
        <a href="{% url 'textbook:index' %}" {% if request.GET.major_category or request.GET.minor_category %}class="to_upper_layer"{% else %}class="bottom_layer"{% endif %}>教材トップ</a>
        {% if request.GET.major_category %}
            <span style="padding: 0 0.25rem">></span>
            {% for major_category in major_categories %}
            {% if request.GET.major_category == major_category.str_id %}
            <a href="?{% url_replace request 'major_category' major_category.id %}" {% if request.GET.minor_category %}class="to_upper_layer"{% else %}class="bottom_layer"{% endif %}>{{ major_category.order }}. {{ major_category.name }}</a>
            {% endif %}
            {% endfor %}
        {% elif request.GET.minor_category %}
            <span style="padding: 0 0.25rem">></span>
            {% for minor_category in minor_categories %}
            {% if request.GET.minor_category == minor_category.str_id %}
            <a href="?{% url_replace request 'major_category' minor_category.parent.id %}" class="to_upper_layer">{{ minor_category.parent.order }}. {{ minor_category.parent.name }}</a>
            <span style="padding: 0 0.25rem">></span>
            <a href="?{% url_replace request 'minor_category' minor_category.id %}" class="bottom_layer">{{ minor_category.parent.order }}-{{ minor_category.order }}. {{ minor_category.name }}</a>
            {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    <div class="d-flex">
        <div class="category_list_area">
            <ul class="major_category_list">
                {% for major_category in major_categories %}
                <li><label for="minor_category_list_chk_{{ major_category.id }}" class="minor_category_list_btn" id="minor_category_list_btn_{{ major_category.id }}">▼</label><a class="category_list_name" href="?{% url_replace request 'major_category' major_category.id %}">{{ major_category.order }}. {{ major_category.name }}</a></li>
                <input type="checkbox" id="minor_category_list_chk_{{ major_category.id }}" class="minor_category_list_chk" style="display: none;" value="{{ major_category.id }}">
                <ul class="minor_category_list">
                    {% for minor_category in minor_categories %}
                    {% if minor_category.parent.id == major_category.id %}
                        <li><a class="category_list_name" href="?{% url_replace request 'minor_category' minor_category.id %}">{{ minor_category.parent.order }}-{{ minor_category.order }}. {{ minor_category.name }}</a></li>
                    {% endif %}
                    {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        </div>
        
        <div class="textbook_list_area">
            <h2 style="margin-left: 0;">教材一覧</h2>
            <div class="textbook_list">
                {% for textbook in textbooks %}
                {% if request.GET.major_category or request.GET.minor_category %}
                <div class="textbook_list_content border p-2">
                    <div class="textbook_title">{{ textbook.title }}</div>
                    <div class="textbook_thumbnail">
                        {% if textbook.is_youtube %}
                        <a href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                            {% if textbook.thumbnail %}
                            <img src="{{ textbook.thumbnail.url }}" alt="">
                            {% elif textbook.thumbnail_url %}
                            <img src="{{ textbook.thumbnail_url }}" alt="">
                            {% else %}
                            <img src="{% static 'images/noimage.png' %}" alt="">
                            {% endif %}
                        </a>
                        <a class="youtube_btn_a" href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                            <label aria-label="再生">
                                <i class="fa-brands fa-youtube"></i>
                            </label>
                        </a>
                        <a class="youtube_btn_center_a" href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                            <div class="play-btn_center"></div>
                        </a>
                        {% else %}
                        <video src="{{ textbook.file_content.url }}" controls {% if textbook.thumbnail %}poster="{{ textbook.thumbnail.url }}"{% endif %}></video>
                        {% endif %}
                    </div>
                    <div class="textbool_explanation">{{ textbook.explanation|default:""|linebreaksbr|urlize }}</div>
                </div>
                {% else %}
                    {% if textbook.is_top %}
                    <div class="textbook_list_content border p-2">
                        <div class="textbook_title">{{ textbook.title }}</div>
                        <div class="textbook_thumbnail">
                            {% if textbook.is_youtube %}
                            <a href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                                {% if textbook.thumbnail %}
                                <img src="{{ textbook.thumbnail.url }}" alt="">
                                {% elif textbook.thumbnail_url %}
                                <img src="{{ textbook.thumbnail_url }}" alt="">
                                {% else %}
                                <img src="{% static 'images/noimage.png' %}" alt="">
                                {% endif %}
                            </a>
                            <a class="youtube_btn_a" href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                                <label aria-label="再生">
                                    <i class="fa-brands fa-youtube"></i>
                                </label>
                            </a>
                            <a class="youtube_btn_center_a" href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                                <div class="play-btn_center"></div>
                            </a>
                            {% else %}
                            <video src="{{ textbook.file_content.url }}" controls {% if textbook.thumbnail %}poster="{{ textbook.thumbnail.url }}"{% endif %}></video>
                            {% endif %}
                        </div>
                        <div class="textbool_explanation">{{ textbook.explanation|default:""|linebreaksbr }}</div>
                    </div>
                    {% endif %}
                {% endif %}
                {% endfor %}
            </div>

            {% if request.user.is_teacher %}
            {% include 'textbook/textbook_form.html' %}
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

templates/textbook/minor_category.html
<option disabled selected>小カテゴリ</option>
{% for minor_category in minor_categories %}
<option value="{{ minor_category.id }}">{{ minor_category.name }}</option>
{% endfor %}

templates/textbook/textbook_form.html
<div style="margin-top: 2rem; min-width: 444px;">
    <h2 style="margin-left: 0;">教材投稿</h2>
    <form action="" method="POST" enctype="multipart/form-data" class="textbook_form">
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="error_message">{{ message }}</div>
        {% endif %}
        {% endfor %}

        {% csrf_token %}
        <div style="margin-left:0.25rem">
            <label class="textbook_form_label">大カテゴリ</label>
            <select name="major_category" id="major_category" class="select_textbook_major_category mr-2" required>
                <option disabled selected>大カテゴリ</option>
                {% for major_category in major_categories %}
                <option value="{{ major_category.id }}">{{ major_category.name }}</option>
                {% endfor %}
            </select>
            <label class="add_textbook_major_category modal_label" for="modal_chk_major" style="font-size:2rem; color: var(--main-color);">
                <i class="fas fa-plus-circle"></i>
            </label>
        </div>
        <div style="margin-left:0.25rem">
            <label class="textbook_form_label">小カテゴリ</label>
            <select name="minor_category" id="minor_category" class="select_textbook_minor_category mr-2" required>
                <option disabled selected>大カテゴリを選択してください</option>
            </select>
            <label class="add_textbook_minor_category modal_label" for="modal_chk_minor" style="font-size:2rem; color: var(--main-color);">
                <i class="fas fa-plus-circle"></i>
            </label>
        </div>
        <div style="margin-left:0.25rem">
            <label class="textbook_form_label">タイトル</label>
            <input type="text" name="title" style="width: calc(100% - 9rem); height: 2rem;" required>
        </div>
        <div style="margin-left:0.25rem">
            <label class="textbook_form_label">表示順</label>
            <input type="number" name="order">
        </div>
        <div style="margin-left:0.25rem">
            <label class="textbook_form_label">サムネイル画像</label>
            <input type="file" name="thumbnail">
        </div>
        <div style="margin-left:0.25rem">
            <label class="textbook_form_label">Youtube動画</label>
            <input type="checkbox" name="is_youtube" id="is_youtube_chk" class="is_youtube_chk" checked>
            <label for="is_youtube_chk" class="is_youtube_label"></label>
        </div>
        <div class="youtube_url" style="margin-left:0.25rem">
            <label class="textbook_form_label">Youtube URL</label>
            <input type="text" name="youtube_url" style="width: calc(100% - 9rem);">
        </div>
        <div class="movie_file" style="margin-left:0.25rem">
            <label class="textbook_form_label">投稿動画</label>
            <input type="file" name="file_content">
        </div>
        <div style="margin-left:0.25rem" class="explanation_area">
            <label class="textbook_form_label">説明文</label>
            <textarea name="explanation"  style="width: calc(100% - 9rem); height: 5rem;"></textarea>
        </div>
        <div style="margin-left:0.25rem">
            <label class="textbook_form_label">トップ画面表示</label>
            <input type="checkbox" name="is_top" id="is_top_chk" class="is_top_chk">
            <label for="is_top_chk" class="is_top_label"></label>
        </div>
        <div class="top_order" style="margin-left:0.25rem">
            <label class="textbook_form_label">トップ画面での表示順</label>
            <input type="number" name="top_order">
        </div>
        <input type="submit" value="送信" class="original_btn original_btn_send">
    </form>
</div>

{# モーダル領域 #}
<input id="modal_chk_major" class="modal_chk" type="checkbox">
<div class="modal_body">
    <label class="modal_bg" for="modal_chk_major"></label>
    <div class="modal_content">
        <h2>大カテゴリ新規追加</h2>
        <form id="textbook_major_category_form" method="POST" action="{% url 'textbook:add_major_category' %}">
            {% csrf_token %}
            <input type="text" name="name" class="form-control" placeholder="大カテゴリ名">
            <div class="form-group mt-2"><label>順番：</label><input type="number" name="order"></div>
            <input class="original_btn" style="padding: 0.2rem 0.5rem;" type="submit" value="登録">
            <label for="modal_chk_major" class="original_btn_cancel">キャンセル</label>
        </form>
        <h2 style="margin-top: 2rem;">大カテゴリ一覧</h2>
        <div id="textbook_major_category_list">
            {% for major_category in major_categories %}
            <label>{{ major_category.name }}</label>
            {% endfor %}
        </div>
    </div>
</div>

<input id="modal_chk_minor" class="modal_chk" type="checkbox">
<div class="modal_body">
    <label class="modal_bg" for="modal_chk_minor"></label>
    <div class="modal_content">
        <h2>小カテゴリ新規追加</h2>
        <form id="textbook_minor_category_form" method="POST" action="{% url 'textbook:add_minor_category' %}">
            {% csrf_token %}
            <div class="mb-2">
                <select name="parent" class="form-control" style="height: 2.5rem;">
                    <option disabled selected>大カテゴリを選択してください</option>
                    {% for major_category in major_categories %}
                    <option value="{{ major_category.id }}">{{ major_category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-2">
                <input type="text" name="name" placeholder="小カテゴリ名" class="form-control">
                <div class="form-group mt-2"><label>順番：</label><input type="number" name="order"></div>
            </div>
            <input class="original_btn" style="padding: 0.2rem 0.5rem;" type="submit" value="登録">
            <label for="modal_chk_minor" class="original_btn_cancel">キャンセル</label>
        </form>
    </div>
</div>