config/urls.py
from django.contrib import admin
from django.urls import path, include

# メディアファイル配信の処理
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("oneall.urls")),
    path("accounts/", include("allauth.urls")),
    path("news/", include("news.urls")),
    path("textbook/", include("textbook.urls")),
    # path("content/", include("content.urls")),
    path("sales/", include("sales.urls")),
    # path("qa/", include("qa.urls")),
    # path("chat/", include("chat.urls")),
    
    path("users/", include("users.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("add_category/", views.add_category, name="add_category"),
]

oneall/urls.py
from django.urls import path
from . import views

app_name = "oneall"
urlpatterns = [
    path("", views.index, name="index"),
]

qa/urls.py
from django.urls import path
from . import views

app_name = "qa"
urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("question_good/<int:pk>/", views.question_good, name="question_good"),
    path("answer_good/<int:q_id>/<int:a_id>/", views.answer_good, name="answer_good"),
]

sales/urls.py
from django.urls import path
from . import views

app_name = "sales"
urlpatterns = [
    path("", views.index, name="index"),
    path("ac/<int:pk>/", views.ac_detail, name="ac_detail"),
    path("q/<int:pk>/", views.q_detail, name="q_detail"),
    path("abc/<int:pk>/", views.abc_detail, name="abc_detail"),
    path("interview/<int:pk>/", views.interview_detail, name="interview_detail"),
    path("contract/<int:pk>/", views.contract_detail, name="contract_detail"),
]

textbook/urls.py
from django.urls import path
from . import views

app_name = "textbook"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("add_major_category/", views.add_major_category, name="add_major_category"),
    path("add_minor_category/", views.add_minor_category, name="add_minor_category"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("members/", views.members, name="members"),
]

oneall/models.py
from django.db import models

# Create your models here.

oneall/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from news.models import News
from textbook.models import Textbook

class IndexView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context                 = {}
        context["newses"]       = News.objects.all().order_by("-dt")[:5]
        context["textbooks"]    = Textbook.objects.all().order_by("top_order", "-dt")

        return render(request, "oneall/index.html", context)

index = IndexView.as_view()

templates/oneall/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
    
    <link rel="stylesheet" href="{% static 'oneall/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'oneall/css/base-sp.css' %}">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    <script src="{% static 'oneall/js/ajax.js' %}"></script>

    {% block extra_head %}
    {% endblock %}
</head>
<body>    
    <div class="container">
        <!-- PC用メニュー -->
        <div class="left-menu">
            <a class="top-page logo-area" href="{% url 'oneall:index' %}">
                <img src="{% static 'images/sesk_logo_221201twht.jpg' %}">
            </a>
            <div class="nav-menu">
                <div class="nav-menu-content" id="nav-menu-home">
                    <a href="{% url 'oneall:index' %}"><i class="fa-solid fa-house" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>HOME</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-news">
                    <a href="{% url 'news:index' %}"><i class="fa-solid fa-circle-info" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>NEWS</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-textbook">
                    <a href="{% url 'textbook:index' %}"><i class="fa-solid fa-book-open" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>TEXTBOOK</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-sales">
                    <a href="{% url 'sales:index' %}"><i class="fa-regular fa-calendar-days" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>SALES DATA</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-member">
                    <a href="{% url 'users:members' %}"><i class="fa-solid fa-people-group" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>STAFF</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-users">
                    <a href="{% url 'users:index' %}"><i class="fa-solid fa-circle-user" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>MyPAGE</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-logout">
                    <a href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>LOGOUT</span></a>
                </div>
            </div>
        </div>

        <!-- スマホ用メニュー -->
        <div class="header-sp">
            <a class="logo-area-sp" href="{% url 'oneall:index' %}">
                <img src="{% static 'images/sesk_logo_221201ywht.jpg' %}">
            </a>
            
            <label class="menu-btn-sp" for="menu-sp_chk"><i class="fa-sharp fa-solid fa-bars"></i></label>
            <input type="checkbox" id="menu-sp_chk">

            <div class="nav-menu-sp">
                <!-- <div id="close_menu">
                    <label for="menu-sp_chk"><i class="fa-sharp fa-solid fa-circle-xmark"></i></label>
                </div> -->
                <div class="nav-menu-content" id="nav-menu-home">
                    <a href="{% url 'oneall:index' %}"><i class="fa-solid fa-house" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>HOME</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-news">
                    <a href="{% url 'news:index' %}"><i class="fa-solid fa-circle-info" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>NEWS</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-textbook">
                    <a href="{% url 'textbook:index' %}"><i class="fa-solid fa-book-open" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>TEXTBOOK</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-sales">
                    <a href="{% url 'sales:index' %}"><i class="fa-regular fa-calendar-days" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>SALES DATA</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-member">
                    <a href="{% url 'users:members' %}"><i class="fa-solid fa-people-group" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>STAFF</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-users">
                    <a href="{% url 'users:index' %}"><i class="fa-solid fa-circle-user" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>MyPAGE</span></a>
                </div>
                <div class="nav-menu-content" id="nav-menu-logout">
                    <a href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt" style="display: inline-block; width: 1.2rem; text-align: center;"></i><span>LOGOUT</span></a>
                </div>
            </div>

            <div class="menu-sp_modal_body">
                <label class="menu-sp_modal_bg" for="menu-sp_chk"></label>
            </div>
        </div>

        <div class="main-contents">
            {% block main %}
            {% endblock %}
        </div>
        </div>
    </div>
</body>
</html>

templates/oneall/index.html
{% extends "oneall/base.html" %}
{% load static %}


{% block extra_head %}
<title>ONE/ALL</title>
<link rel="stylesheet" href="{% static 'oneall/css/index.css' %}">
<link rel="stylesheet" href="{% static 'oneall/css/index-sp.css' %}">
<!-- <link rel="stylesheet" href="{% static 'news/css/index.css' %}">
<link rel="stylesheet" href="{% static 'textbook/css/index.css' %}"> -->
{% endblock %}


{% block main %}
<h1>HOME</h1>
<section>
    <h2>新着情報</h2>
    <div class="news_list">
        {% for news in newses %}
        <a class="news_list_content border d-flex flex-wrap align-items-center" href="{% url 'news:detail' news.id %}">
            <div class="news_dt">{{ news.dt|date:'Y/m/d' }}</div>
            <div class="news_category"><label class="news_category_label">{{ news.category.name|default:'未分類' }}</label></div>
            <div class="news_title">{{ news.title }}</div>
        </a>
        {% endfor %}
    </div>
</section>
<section>
    <h2>教材</h2>
    <div class="textbook_list">
        {% for textbook in textbooks %}
        {% if textbook.is_top %}
            <div class="textbook_list_content border p-2">
                <div class="textbook_title">{{ textbook.title }}</div>
                <div class="textbook_thumbnail">
                    {% if textbook.is_youtube %}
                    <a href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                        {% if textbook.thumbnail %}
                        <img src="{{ textbook.thumbnail.url }}" alt="">
                        {% elif textbook.thumbnail_url %}
                        <img src="{{ textbook.thumbnail_url }}" alt="">
                        {% else %}
                        <img src="{% static 'images/noimage.png' %}" alt="">
                        {% endif %}
                    </a>
                    <a class="youtube_btn_a" href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                        <label aria-label="再生">
                            <i class="fa-brands fa-youtube"></i>
                        </label>
                    </a>
                    <a class="youtube_btn_center_a" href="{{ textbook.youtube_url }}" target="_blank" rel="noopener noreferrer">
                        <div class="play-btn_center"></div>
                    </a>
                    {% else %}
                    <video src="{{ textbook.file_content.url }}" controls {% if textbook.thumbnail %}poster="{{ textbook.thumbnail.url }}"{% endif %}></video>
                    {% endif %}
                </div>
            </div>
        {% endif %}
        {% endfor %}
    </div>
</section>
{% endblock %}

templates/oneall/notfound.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'oneall/css/base.css' %}">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>
<body>
    <h1 class="text-center mt-1">404 Not Found</h1>
    <div class="text-center">お探しのページは見つかりません。</div>
    <div class="text-center"><a href="{% url 'oneall:index' %}">トップページに戻る</a></div>
</body>
</html>