config/urls.py
from django.contrib import admin
from django.urls import path, include

# メディアファイル配信の処理
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("oneall.urls")),
    path("accounts/", include("allauth.urls")),
    path("news/", include("news.urls")),
    path("textbook/", include("textbook.urls")),
    # path("content/", include("content.urls")),
    path("sales/", include("sales.urls")),
    # path("qa/", include("qa.urls")),
    # path("chat/", include("chat.urls")),
    
    path("users/", include("users.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from . import views

app_name = "qa"
urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("question_good/<int:pk>/", views.question_good, name="question_good"),
    path("answer_good/<int:q_id>/<int:a_id>/", views.answer_good, name="answer_good"),
]

sales/urls.py
from django.urls import path
from . import views

app_name = "sales"
urlpatterns = [
    path("", views.index, name="index"),
    path("ac/<int:pk>/", views.ac_detail, name="ac_detail"),
    path("q/<int:pk>/", views.q_detail, name="q_detail"),
    path("abc/<int:pk>/", views.abc_detail, name="abc_detail"),
    path("interview/<int:pk>/", views.interview_detail, name="interview_detail"),
    path("contract/<int:pk>/", views.contract_detail, name="contract_detail"),
]

sales/models.py
from django.db import models
from django.conf import settings

from django.utils import timezone

class AC(models.Model):
    dt      = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.CASCADE)

    ac_date = models.DateTimeField(verbose_name="AC日時")
    c_name  = models.CharField(verbose_name="Cさんの名前", max_length=10, null=True, blank=True)
    place   = models.CharField(verbose_name="AC場所", max_length=200, null=True, blank=True)

    c_is_ac_active = models.BooleanField(verbose_name="ACステータス", default=True)

    def __str__(self):
        return self.c_name

    def str_id(self):
        return str(self.id)


class Question(models.Model):
    dt      = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.CASCADE)

    q_date  = models.DateField(verbose_name="質問日")
    ac      = models.ForeignKey(AC, verbose_name="対応するAC", on_delete=models.CASCADE)

    c_is_question_active    = models.BooleanField(verbose_name="質問ステータス", default=True)

    def __str__(self):
        return self.ac.c_name


class ABC(models.Model):
    dt          = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.CASCADE)

    abc_date    = models.DateTimeField(verbose_name="ABC日時")
    question    = models.ForeignKey(Question, verbose_name="対応する質問", on_delete=models.CASCADE)

    c_is_abc_active = models.BooleanField(verbose_name="ABCステータス", default=True)

    def __str__(self):
        return self.question.ac.c_name


class Interview(models.Model):
    dt              = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.CASCADE)

    interview_date  = models.DateTimeField(verbose_name="面談日時")
    abc             = models.ForeignKey(ABC, verbose_name="対応するABC", on_delete=models.CASCADE)

    c_is_interview_active    = models.BooleanField(verbose_name="面談ステータス", default=True)

    def __str__(self):
        return self.abc.question.ac.c_name


class Contract(models.Model):
    dt              = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.CASCADE)

    contract_date   = models.DateField(verbose_name="契約日時")
    interview       = models.ForeignKey(Interview, verbose_name="対応する面談", on_delete=models.CASCADE)

    def __str__(self):
        return self.interview.abc.question.ac.c_name

sales/forms.py
from django import forms
from .models import AC, Question, ABC, Interview, Contract

from django.core.validators import MinValueValidator, MaxValueValidator


class ACForm(forms.ModelForm):

    class Meta:
        model   = AC
        fields  = ["user","ac_date","c_name","place"]


class QuestionForm(forms.ModelForm):

    class Meta:
        model   = Question
        fields  = ["user","q_date","ac"]
    

class ABCForm(forms.ModelForm):

    class Meta:
        model   = ABC
        fields  = ["user","abc_date","question"]


class InterviewForm(forms.ModelForm):

    class Meta:
        model   = Interview
        fields  = ["user","interview_date","abc"]


class ContractForm(forms.ModelForm):

    class Meta:
        model   = Contract
        fields  = ["user","contract_date","interview"]


# 年月検索用バリデーションフォーム
class YearMonthForm(forms.Form):
    year    = forms.IntegerField()
    month   = forms.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])

sales/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.views import View
from rest_framework.views import APIView as View

from django.db.models import Q
from django.db.models import Sum

from .models import AC, Question, ABC, Interview, Contract
from .forms import ACForm, QuestionForm, ABCForm, InterviewForm, ContractForm, YearMonthForm

from users.models import CustomUser

from . import calender, set_selected_date
from . import term_sales_data, teacher_sales_data
from . import change_status

import datetime

from django.http import HttpResponseNotFound
from django.http.response import JsonResponse
from django.template.loader import render_to_string

from  pytz import timezone


class IndexView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context = {}

        jst     = timezone('Asia/Tokyo')
        today   = datetime.datetime.now(tz=jst)

        selected_date               = set_selected_date.set(request, jst, today)
        context["selected_date"]    = selected_date

        context["months"]   = [ i for i in range(1,13) ]
        context["years"]    = calender.create_years(request, selected_date, today)
        context["next_month"], context["last_month"]    = calender.create_months(selected_date)
        context["calender"] = calender.create_calender(selected_date.year, selected_date.month)

        if request.user.is_teacher:
            context["acs"]          = AC.objects.all().order_by("-ac_date")
            context["questions"]    = Question.objects.all().order_by("-q_date")
            context["abcs"]         = ABC.objects.all().order_by("-abc_date")
            context["interviews"]   = Interview.objects.all().order_by("-interview_date")
            context["contracts"]    = Contract.objects.all().order_by("-contract_date")

            context["students"]     = CustomUser.objects.filter(is_student=True).order_by("date_joined")
            context["monthly_sales_datas"]  = teacher_sales_data.monthly(request, selected_date)
            context["yearly_sales_datas"]   = teacher_sales_data.yearly(request, selected_date)

        else:
            context["acs"]          = AC.objects.filter(user=request.user.id).order_by("-ac_date")
            context["questions"]    = Question.objects.filter(user=request.user.id).order_by("-q_date")
            context["abcs"]         = ABC.objects.filter(user=request.user.id).order_by("-abc_date")
            context["interviews"]   = Interview.objects.filter(user=request.user.id).order_by("-interview_date")
            context["contracts"]    = Contract.objects.filter(user=request.user.id).order_by("-contract_date")
            
            context["monthly_sales_datas"]  = term_sales_data.monthly(request, selected_date)
            context["yearly_sales_datas"]   = term_sales_data.yearly(request, selected_date)

            change_status.change_inactive(request, today)
            # acs     = AC.objects.filter(user=request.user.id)
            # for ac in acs:
            #     if ac.c_is_ac_active and (ac.ac_date + tz.timedelta(days=21) < today):
            #         print(ac.ac_date)
            #         ac.c_is_ac_active = False
            #         ac.save()
        

        return render(request, "sales/index.html", context)
    

    def post(self, request, *args, **kwargs):
        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        if copied["sales_form_chk"] == "ac":
            form        = ACForm(copied)
            if not form.is_valid():
                print("バリデーションNG")
                print(form.errors)
                return redirect("sales:index")
        elif copied["sales_form_chk"] == "question":
            form        = QuestionForm(copied)
            if not form.is_valid():
                print("バリデーションNG")
                print(form.errors)
                return redirect("sales:index")
            
            ac          = AC.objects.filter(id=request.POST["ac"]).first()
            ac.c_is_ac_active  = False
            ac.save()
        elif copied["sales_form_chk"] == "abc":
            form        = ABCForm(copied)
            if not form.is_valid():
                print("バリデーションNG")
                print(form.errors)
                return redirect("sales:index")
            
            q                       = Question.objects.filter(id=request.POST["question"]).first()
            q.c_is_question_active  = False
            q.save()
        elif copied["sales_form_chk"] == "interview":
            form        = InterviewForm(copied)
            if not form.is_valid():
                print("バリデーションNG")
                print(form.errors)
                return redirect("sales:index")
            
            abc                 = ABC.objects.filter(id=request.POST["abc"]).first()
            abc.c_is_abc_active = False
            abc.save()
        else:
            form        = ContractForm(copied)
            if not form.is_valid():
                print("バリデーションNG")
                print(form.errors)
                return redirect("sales:index")
            
            interview                       = Interview.objects.filter(id=request.POST["interview"]).first()
            interview.c_is_interview_active = False
            interview.save()
        
        form.save()

        return redirect("sales:index")


index = IndexView.as_view()


class ACDetailView(LoginRequiredMixin,View):

    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["ac"]   = AC.objects.filter(id=pk).first()
        return render(request, "sales/ac_detail.html", context)
    
    def delete(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }
        ac      = AC.objects.filter(id=pk).first()
        if ac:
            ac.delete()
            data["error"] = False

        return JsonResponse(data)
    
    def put(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }

        ac              = AC.objects.filter(id=pk).first()
        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form    = ACForm(copied, instance=ac)

        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return JsonResponse(data)
        
        form.save()
        data["error"]   = False

        return JsonResponse(data)
    
ac_detail = ACDetailView.as_view()


class QuestionDetailView(LoginRequiredMixin,View):

    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["q"]    = Question.objects.filter(id=pk).first()
        context["acs"]  = AC.objects.filter(user=request.user.id).order_by("-ac_date")
        return render(request, "sales/q_detail.html", context)
    
    def delete(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }
        q       = Question.objects.filter(id=pk).first()
        if q:
            q.delete()
            data["error"] = False

        return JsonResponse(data)
    
    def put(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }

        q               = Question.objects.filter(id=pk).first()
        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form    = QuestionForm(copied, instance=q)

        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return JsonResponse(data)
        
        form.save()
        data["error"]   = False

        return JsonResponse(data)

q_detail = QuestionDetailView.as_view()


class ABCDetailView(LoginRequiredMixin,View):

    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["abc"]  = ABC.objects.filter(id=pk).first()
        context["questions"]    = Question.objects.filter(user=request.user.id).order_by("-q_date")
        return render(request, "sales/abc_detail.html", context)
        
    def delete(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }
        abc     = ABC.objects.filter(id=pk).first()
        if abc:
            abc.delete()
            data["error"] = False

        return JsonResponse(data)
    
    def put(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }

        abc             = ABC.objects.filter(id=pk).first()
        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form    = ABCForm(copied, instance=abc)

        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return JsonResponse(data)
        
        form.save()
        data["error"]   = False

        return JsonResponse(data)

abc_detail = ABCDetailView.as_view()


class InterviewDetailView(LoginRequiredMixin,View):

    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["interview"]    = Interview.objects.filter(id=pk).first()
        context["abcs"]         = ABC.objects.filter(user=request.user.id).order_by("-abc_date")
        return render(request, "sales/interview_detail.html", context)

    def delete(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }
        interview   = Interview.objects.filter(id=pk).first()
        if interview:
            interview.delete()
            data["error"] = False

        return JsonResponse(data)
    
    def put(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }

        interview       = Interview.objects.filter(id=pk).first()
        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form    = InterviewForm(copied, instance=interview)

        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return JsonResponse(data)
        

templates/sales/abc_detail.html
{% extends "oneall/base.html" %}
{% load static %}


{% block extra_head %}
<title>営業データ －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'sales/css/index.css' %}">
<link rel="stylesheet" href="{% static 'sales/css/detail.css' %}">
<script>
    let DELETE_URL  = "{% url 'sales:abc_detail' 1 %}";
    let RETURN_URL  = "{% url 'sales:index' %}"
</script>
<script src="{% static 'sales/js/detail.js' %}"></script>
{% endblock %}


{% block main %}
<h1>SALES DATA</h1>
<div class="sales_data_detail border">
    <input type="checkbox" id="abc_edit_chk" class="sales_data_edit_chk">
    <div class="sales_data_icons">
        <label class="sales_data_icon edit" value="{{ abc.id }}" for="abc_edit_chk"><i class="fa-solid fa-pen"></i></label>
        <button class="sales_data_icon trash" value="{{ abc.id }}"><i class="fa-solid fa-trash-can"></i></button>
    </div>
    
    <div class="sales_data_detail_content">
        <h3>ABC</h3>
        <div>Cさんの名前：{{ abc.question.ac.c_name }}</div>
        <div>ABC日時：{{ abc.abc_date|date:'Y/m/d H:i' }}</div>
    </div>
    <!-- 編集フォーム -->
    <div class="sales_data_detail_edit">
        <form action="{% url 'sales:abc_detail' abc.id %}" id="abc_edit_form">
            <input class="date_time" name="abc_date" value="{{ abc.abc_date }}">
            <select name="question" class="form-control" style="height:2.3rem;" required>
                {% for question in questions %}
                <option value="{{ question.id }}" {% if abc.question.id == question.id %}selected{% endif %}>{{ question.ac.c_name }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-primary" id="submit_edit" data-salestype="abc">編集</button>
            <label for="abc_edit_chk" class="btn btn-danger mt-2">キャンセル</label>
        </form>
    </div>
</div>
{% endblock %}

templates/sales/ac_detail.html
{% extends "oneall/base.html" %}
{% load static %}


{% block extra_head %}
<title>営業データ －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'sales/css/index.css' %}">
<link rel="stylesheet" href="{% static 'sales/css/detail.css' %}">
<script>
    let DELETE_URL  = "{% url 'sales:ac_detail' 1 %}";
    let RETURN_URL  = "{% url 'sales:index' %}"
</script>
<script src="{% static 'sales/js/detail.js' %}"></script>
{% endblock %}


{% block main %}
<h1>SALES DATA</h1>
<div class="sales_data_detail border">
    <input type="checkbox" id="ac_edit_chk" class="sales_data_edit_chk">
    <div class="sales_data_icons">
        <label class="sales_data_icon edit" value="{{ ac.id }}" for="ac_edit_chk"><i class="fa-solid fa-pen"></i></label>
        <button class="sales_data_icon trash" value="{{ ac.id }}"><i class="fa-solid fa-trash-can"></i></button>
    </div>
    
    <div class="sales_data_detail_content">
        <h3>AC</h3>
        <div>Cさんの名前：{{ ac.c_name }}</div>
        <div>AC日時：{{ ac.ac_date|date:'Y/m/d H:i' }}</div>
        {% if ac.place %}
        <div>場所：{{ ac.place|linebreaksbr|default:'' }}</div>
        {% endif %}
    </div>
    <!-- 編集フォーム -->
    <div class="sales_data_detail_edit">
        <form action="{% url 'sales:ac_detail' ac.id %}" id="ac_edit_form">
            {% csrf_token %}
            <input class="date_time" name="ac_date" value="{{ ac.ac_date }}">
            <input type="text" name="c_name" value="{{ ac.c_name }}">
            <input type="text" name="place" {% if ac.place %}value="{{ ac.place }}"{% endif %}>
            <button class="btn btn-primary" id="submit_edit" data-salestype="ac">編集</button>
            <label for="ac_edit_chk" class="btn btn-danger mt-2">キャンセル</label>
        </form>
    </div>
</div>
{% endblock %}

templates/sales/calender.html
{% include "sales/calender_header.html" %}
<table class="calender">
    <thead class="calender_head">
        <tr>
            <td>日</td>
            <td>月</td>
            <td>火</td>
            <td>水</td>
            <td>木</td>
            <td>金</td>
            <td>土</td>
        </tr>
    </thead>
    <tbody>
        {% for week in calender %}
        <tr>
            {% for date in week %}
            <td class="create_sales_data" data-day="{{ date.day }}">
                <div class="calender_day">{{ date.day }}</div>
                {% if request.user.is_student %}
                {% for ac in acs %}
                {% if ac.ac_date.year == selected_date.year and ac.ac_date.month == selected_date.month and date.day == ac.ac_date.day %}
                <div class="sales_data_label_parent">
                    <a class="sales_data_lebel ac_label" href="{% url 'sales:ac_detail' ac.id %}">AC</a>
                    <label class="sales_data_c_name">{{ ac.c_name }}</label>
                </div>
                {% endif %}
                {% endfor %}

                {% for q in questions %}
                {% if q.q_date.year == selected_date.year and q.q_date.month == selected_date.month and date.day == q.q_date.day %}
                <div class="sales_data_label_parent">
                    <a class="sales_data_lebel q_label" href="{% url 'sales:q_detail' q.id %}">質問</a>
                    <label class="sales_data_c_name">{{ q.ac.c_name }}</label>
                </div>
                {% endif %}
                {% endfor %}

                {% for abc in abcs %}
                {% if abc.abc_date.year == selected_date.year and abc.abc_date.month == selected_date.month and date.day == abc.abc_date.day %}
                <div class="sales_data_label_parent">
                    <a class="sales_data_lebel abc_label"href="{% url 'sales:abc_detail' abc.id %}">ABC</a>
                    <label class="sales_data_c_name">{{ abc.question.ac.c_name }}</label>
                </div>
                {% endif %}
                {% endfor %}
                
                {% for interview in interviews %}
                {% if interview.interview_date.year == selected_date.year and interview.interview_date.month == selected_date.month and date.day == interview.interview_date.day %}
                <div class="sales_data_label_parent">
                    <a class="sales_data_lebel interview_label" href="{% url 'sales:interview_detail' interview.id %}">面談</a>
                    <label class="sales_data_c_name">{{ interview.abc.question.ac.c_name }}</label>
                </div>
                {% endif %}
                {% endfor %}

                {% for contract in contracts %}
                {% if contract.contract_date.year == selected_date.year and contract.contract_date.month == selected_date.month and date.day == contract.contract_date.day %}
                <div class="sales_data_label_parent">
                    <a class="sales_data_lebel contract_label" href="{% url 'sales:contract_detail' contract.id %}">契約</a>
                    <label class="sales_data_c_name">{{ contract.interview.abc.question.ac.c_name }}</label>
                </div>
                {% endif %}
                {% endfor %}
                {% endif %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if request.user.is_student %}
<div class="add_sales_data">
    <label class="modal_label" for="modal_chk" style="font-size:2.5rem; color: var(--main-color);">
        <i class="fas fa-plus-circle"></i>
    </label>
</div>
{% endif %}

templates/sales/contract_detail.html
{% extends "oneall/base.html" %}
{% load static %}


{% block extra_head %}
<title>営業データ －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'sales/css/index.css' %}">
<link rel="stylesheet" href="{% static 'sales/css/detail.css' %}">
<script>
    let DELETE_URL  = "{% url 'sales:contract_detail' 1 %}";
    let RETURN_URL  = "{% url 'sales:index' %}"
</script>
<script src="{% static 'sales/js/detail.js' %}"></script>
{% endblock %}


{% block main %}
<h1>SALES DATA</h1>
<div class="sales_data_detail border">
    <input type="checkbox" id="contract_edit_chk" class="sales_data_edit_chk">
    <div class="sales_data_icons">
        <label class="sales_data_icon edit" value="{{ contract.id }}" for="contract_edit_chk"><i class="fa-solid fa-pen"></i></label>
        <button class="sales_data_icon trash" value="{{ contract.id }}"><i class="fa-solid fa-trash-can"></i></button>
    </div>
    
    <div class="sales_data_detail_content">
        <h3>契約</h3>
        <div>Cさんの名前：{{ contract.interview.abc.question.ac.c_name }}</div>
        <div>契約日：{{ contract.contract_date|date:'Y/m/d' }}</div>
    </div>
    <!-- 編集フォーム -->
    <div class="sales_data_detail_edit">
        <form action="{% url 'sales:contract_detail' contract.id %}" id="contract_edit_form">
            <input class="date" name="contract_date" value="{{ contract.contract_date }}">
            <select name="interview" class="form-control" style="height:2.3rem;" required>
                {% for interview in interviews %}
                <option value="{{ interview.id }}" {% if contract.interview.id == interview.id %}selected{% endif %}>{{ interview.abc.question.ac.c_name }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-primary" id="submit_edit" data-salestype="contract">編集</button>
            <label for="contract_edit_chk" class="btn btn-danger mt-2">キャンセル</label>
        </form>
    </div>
</div>
{% endblock %}

templates/sales/interview_detail.html
{% extends "oneall/base.html" %}
{% load static %}


{% block extra_head %}
<title>営業データ －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'sales/css/index.css' %}">
<link rel="stylesheet" href="{% static 'sales/css/detail.css' %}">
<script>
    let DELETE_URL  = "{% url 'sales:interview_detail' 1 %}";
    let RETURN_URL  = "{% url 'sales:index' %}"
</script>
<script src="{% static 'sales/js/detail.js' %}"></script>
{% endblock %}


{% block main %}
<h1>SALES DATA</h1>
<div class="sales_data_detail border">
    <input type="checkbox" id="interview_edit_chk" class="sales_data_edit_chk">
    <div class="sales_data_icons">
        <label class="sales_data_icon edit" value="{{ interview.id }}" for="interview_edit_chk"><i class="fa-solid fa-pen"></i></label>
        <button class="sales_data_icon trash" value="{{ interview.id }}"><i class="fa-solid fa-trash-can"></i></button>
    </div>
    
    <div class="sales_data_detail_content">
        <h3>面談</h3>
        <div>Cさんの名前：{{ interview.abc.question.ac.c_name }}</div>
        <div>質問日：{{ interview.interview_date|date:'Y/m/d H:i' }}</div>
    </div>
    <!-- 編集フォーム -->
    <div class="sales_data_detail_edit">
        <form action="{% url 'sales:interview_detail' interview.id %}" id="interview_edit_form">
            <input class="date_time" name="interview_date" value="{{ interview.interview_date }}">
            <select name="abc" class="form-control" style="height:2.3rem;" required>
                {% for abc in abcs %}
                <option value="{{ abc.id }}" {% if interview.abc.id == abc.id %}selected{% endif %}>{{ abc.question.ac.c_name }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-primary" id="submit_edit" data-salestype="interview">編集</button>
            <label for="interview_edit_chk" class="btn btn-danger mt-2">キャンセル</label>
        </form>
    </div>
</div>
{% endblock %}

templates/sales/q_detail.html
{% extends "oneall/base.html" %}
{% load static %}


{% block extra_head %}
<title>営業データ －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'sales/css/index.css' %}">
<link rel="stylesheet" href="{% static 'sales/css/detail.css' %}">
<script>
    let DELETE_URL  = "{% url 'sales:q_detail' 1 %}";
    let RETURN_URL  = "{% url 'sales:index' %}"
</script>
<script src="{% static 'sales/js/detail.js' %}"></script>
{% endblock %}


{% block main %}
<h1>SALES DATA</h1>
<div class="sales_data_detail border">
    <input type="checkbox" id="q_edit_chk" class="sales_data_edit_chk">
    <div class="sales_data_icons">
        <label class="sales_data_icon edit" value="{{ q.id }}" for="q_edit_chk"><i class="fa-solid fa-pen"></i></label>
        <button class="sales_data_icon trash" value="{{ q.id }}"><i class="fa-solid fa-trash-can"></i></button>
    </div>
    
    <div class="sales_data_detail_content">
        <h3>質問</h3>
        <div>Cさんの名前：{{ q.ac.c_name }}</div>
        <div>質問日：{{ q.q_date|date:'Y/m/d' }}</div>
    </div>
    <!-- 編集フォーム -->
    <div class="sales_data_detail_edit">
        <form action="{% url 'sales:q_detail' q.id %}" id="q_edit_form">
            {% csrf_token %}
            <input class="date" name="q_date" value="{{ q.q_date }}">
            <select name="ac" class="form-control" style="height:2.3rem;" required>
                {% for ac in acs %}
                <option value="{{ ac.id }}" {% if q.ac.id == ac.id %}selected{% endif %}>{{ ac.c_name }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-primary" id="submit_edit" data-salestype="q">編集</button>
            <label for="q_edit_chk" class="btn btn-danger mt-2">キャンセル</label>
        </form>
    </div>
</div>
{% endblock %}