config/urls.py
from django.contrib import admin
from django.urls import path, include

# メディアファイル配信の処理
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("oneall.urls")),
    path("accounts/", include("allauth.urls")),
    path("news/", include("news.urls")),
    path("textbook/", include("textbook.urls")),
    # path("content/", include("content.urls")),
    path("sales/", include("sales.urls")),
    # path("qa/", include("qa.urls")),
    # path("chat/", include("chat.urls")),
    
    path("users/", include("users.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("add_category/", views.add_category, name="add_category"),
]

oneall/urls.py
from django.urls import path
from . import views

app_name = "oneall"
urlpatterns = [
    path("", views.index, name="index"),
]

qa/urls.py
from django.urls import path
from . import views

app_name = "qa"
urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("question_good/<int:pk>/", views.question_good, name="question_good"),
    path("answer_good/<int:q_id>/<int:a_id>/", views.answer_good, name="answer_good"),
]

news/models.py
from django.db import models
from django.conf import settings

from django.utils import timezone

class Category(models.Model):
    name    = models.CharField(verbose_name="カテゴリ名", max_length=10, unique=True)

    def __str__(self):
        return self.name

    def str_id(self):
        return str(self.id)


class News(models.Model):
    dt          = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.SET_NULL, null=True, blank=True)

    title       = models.CharField(verbose_name="タイトル", max_length=100)
    content     = models.CharField(verbose_name="内容", max_length=2000)

    category    = models.ForeignKey(Category, verbose_name="ニュースカテゴリ", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from .models import News, Category

class NewsForm(forms.ModelForm):

    class Meta:
        model   = News
        fields  = ["title","content","user","category"]


class CategorySearchForm(forms.ModelForm):

    class Meta:
        model   = News
        fields  = ["category"]


class CategoryForm(forms.ModelForm):

    class Meta:
        model   = Category
        fields  = ["name"]

        error_messages = {
            'name': {
                'max_length': "カテゴリ名が" + str(Category.name.field.max_length) + "文字を超えています。",
                'required': "カテゴリ名を入力してください。",
                'unique' : "同一のカテゴリ名が既に存在します。",
            },
        }

news/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.views import View
from rest_framework.views import APIView as View

from django.db.models import Q
from django.core.paginator import Paginator

from .models import Category, News
from .forms import NewsForm, CategorySearchForm, CategoryForm

from django.contrib import messages

from django.http import HttpResponseNotFound
from django.http.response import JsonResponse
from django.template.loader import render_to_string

class IndexView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context = {}
        query   = Q()

        if "search" in request.GET:
            search      = request.GET["search"]
            raw_words   = search.replace("　"," ").split(" ")
            words       = [ w for w in raw_words if w != ""]

            for w in words:
                query &= Q(title__contains=w)
        
        form    = CategorySearchForm(request.GET)
        if form.is_valid():
            cleaned = form.clean()
            # ForeignKeyをバリデーション、clean()して得られる値は、紐づいているモデルオブジェクト。
            query   &= Q(category=cleaned["category"].id)

        newses      = News.objects.filter(query).order_by("-dt")
        paginator   = Paginator(newses, 10)

        if "page" in request.GET:
            context["newses"]   = paginator.get_page(request.GET["page"])
        else:
            context["newses"]   = paginator.get_page(1)
        
        # context["newses"]       = News.objects.filter(query).order_by("-dt")
        context["categories"]   = Category.objects.all()

        return render(request, "news/index.html", context)

    def post(self, request, *args, **kwargs):

        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form    = NewsForm(copied)

        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return redirect("news:index")

        print("バリデーションOK")
        form.save()

        return redirect("news:index")

index = IndexView.as_view()


class NewsDetailView(LoginRequiredMixin,View):
    def get(self, request, pk, *args, **kwargs):
        context         = {}

        news    = News.objects.filter(id=pk).first()
        if not news:

            # return redirect("news:index")
            return HttpResponseNotFound(render_to_string("oneall/notfound.html"))
        
        context["news"] = news
        if request.user.is_teacher:
            context["categories"]   = Category.objects.all()

        return render(request, "news/detail.html", context)
    

    def delete(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }

        news    = News.objects.filter(id=pk).first()
        if news:
            news.delete()
            data["error"] = False

        return JsonResponse(data)
    

    def put(self, request, pk, *args, **kwargs):
        
        data    = { "error": True }

        news            = News.objects.filter(id=pk).first()
        copied          = request.POST.copy()
        copied["user"]  = request.user.id

        form    = NewsForm(copied, instance=news)

        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return JsonResponse(data)
        
        form.save()
        data["error"]   = False

        return JsonResponse(data)
    

detail = NewsDetailView.as_view()


class AddCategoryView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):

        categories  = Category.objects.all()
        copied      = request.POST.copy()
        
        form    = CategoryForm(copied)
        if not form.is_valid():
            print(form.errors)
            
            values  = form.errors.get_json_data().values()
            for value in values:
                for v in value:
                    messages.error(request, v["message"])
            
            return redirect("news:index")
        
        print("バリデーションOK")
        form.save()

        return redirect("news:index")


add_category = AddCategoryView.as_view()

templates/news/detail.html
{% extends "oneall/base.html" %}
{% load static %}


{% block extra_head %}
<title>NEWS －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'news/css/index.css' %}">
<link rel="stylesheet" href="{% static 'news/css/detail.css' %}">
<script>
    let DELETE_URL  = "{% url 'news:detail' 1 %}";
    let RETURN_URL  = "{% url 'news:index' %}"
</script>
<script src="{% static 'news/js/detail.js' %}"></script>
{% endblock %}

{% block main %}
<h1>NEWS</h1>
<div class="nav_link">
    <a href="{% url 'oneall:index' %}" class="to_upper_layer">ホーム</a>
    <span style="padding: 0 0.25rem">></span>
    <a href="{% url 'news:index' %}" class="to_upper_layer">お知らせ一覧</a>
    <span style="padding: 0 0.25rem">></span>
    <a href="" class="bottom_layer">{{ news.title }}</a>
</div>
<div class="news_detail border">
    {% if request.user.is_teacher %}
    <input type="checkbox" id="news_edit_chk">
    <div class="news_icons">
        <label class="news_icon edit" value="{{ news.id }}" for="news_edit_chk"><i class="fa-solid fa-pen"></i></label>
        <button class="news_icon trash" value="{{ news.id }}"><i class="fa-solid fa-trash-can"></i></button>
    </div>
    {% endif %}
    <div class="news_detail_content">
        <h3>{{ news.title }}</h3>
        <div style="margin: 0.75rem 0 0.5rem 0.5rem;"><label class="news_category_label">{{ news.category.name|default:'未分類' }}</label><span style="font-size: 0.9rem; margin-left: 1rem; color: var(--tag-color);">{{ news.dt|date:'Y/m/d' }}</span><span style="font-size: 0.9rem; margin-left: 1rem; color: var(--tag-color);">{{ news.user.handle_name }}</span></div>
        <div class="mt-3 ml-2">{{ news.content|linebreaksbr|urlize }}</div>
    </div>
    <!-- 編集フォーム -->
    <div class="news_detail_edit">
        <form action="{% url 'news:detail' news.id %}" id="news_edit_form">
            {% csrf_token %}
            <h3><input type="text" name="title" value="{{ news.title }}"></h3>
            <select name="category">
                {% for category in categories %}
                <option value="{{ category.id }}" {% if category.id == news.category.id %}selected{% endif %}>{{ category.name }}</option>
                {% endfor %}
            </select>
            <div><span>{{ news.dt }}</span><span style="margin-left: 1rem;">{{ news.user.handle_name }}</span></div>
            <textarea name="content" class="form-control" rows="10">{{ news.content }}</textarea>
            <button class="btn btn-primary" id="submit_edit">編集</button>
            <label for="news_edit_chk" class="btn btn-danger mt-2">キャンセル</label>
        </form>
    </div>
</div>
{% endblock %}

templates/news/index.html
{% extends "oneall/base.html" %}
{% load static %}
{% load param_change %}


{% block extra_head %}
<title>NEWS －ONE/ALL</title>
<link rel="stylesheet" href="{% static 'news/css/index.css' %}">
<link rel="stylesheet" href="{% static 'news/css/news_form.css' %}">
<link rel="stylesheet" href="{% static 'oneall/css/modal_diagram.css' %}">

<script src="{% static 'oneall/js/ajax.js' %}"></script>
<script src="{% static 'news/js/index.js' %}"></script>
<script src="{% static 'news/js/news_form.js' %}"></script>
{% endblock %}


{% block main %}
<div class="d-flex justify-content-between flex-wrap">
    <div>
        <h1>NEWS</h1>
    </div>
    <div>
        <div class="news_search">
            <form action="" id="news_search_form" class="input-group">
                <select name="category" class="not_basecss">
                    <option value="">カテゴリ</option>
                    {% for category in categories %}
                    <option value="{{ category.id }}" {% if request.GET.category == category.str_id %}selected{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
                <input class="form-control" type="text" name="search" placeholder="タイトルから検索" value="{{ request.GET.search }}">
                <div class="input-group-append">
                    <button id="search" class="form-control btn btn-outline-primary">検索</button>
                </div>
            </form>
        </div>
    </div>
</div>
<section>
    <h2>お知らせ一覧</h2>
    <div class="news_list">
        {% for news in newses %}
        <a class="news_list_content border d-flex flex-wrap align-items-center" href="{% url 'news:detail' news.id %}">
            <div class="news_dt">{{ news.dt|date:'Y/m/d' }}</div>
            <div class="news_category"><label class="news_category_label">{{ news.category.name|default:'未分類' }}</label></div>
            <div class="news_title">{{ news.title }}</div>
        </a>
        {% endfor %}
    </div>
    <ul class="pagination justify-content-center" style="margin-top: 1rem;">
        {% if newses.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' '1' %}">1</a></li>
            {% if newses.previous_page_number != 1 %}
            <li class="page-item"><span class="page-link page-no-link">&hellip;</span></li>
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' newses.previous_page_number %}">{{ newses.previous_page_number }}</a></li>
            {% endif %}
        {% endif %}
        <li class="page-item"><span class="page-link page-no-link">{{ newses.number }}</span></li>
        {% if newses.has_next %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' newses.next_page_number %}">{{ newses.next_page_number }}</a></li>
            {% if newses.next_page_number != newses.paginator.num_pages %}
                <li class="page-item"><span class="page-link page-no-link">&hellip;</span></li>
                <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' newses.paginator.num_pages %}">{{ newses.paginator.num_pages }}</a></li>
            {% endif %}
        {% endif %}
    </ul>
</section>

{% if request.user.is_teacher %}
{% include 'news/news_form.html' %}
{% endif %}
{% endblock %}

templates/news/news_form.html
<section>
    <h2>お知らせ記事投稿フォーム</h2>
    <form id="news_form" method="POST">
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="error_message">{{ message }}</div>
        {% endif %}
        {% endfor %}

        {% csrf_token %}
        <input type="text" name="title" class="form-control" placeholder="タイトル" required>
        <div class="d-flex align-items-center">
            <select name="category" class="select_news_category mr-2" required>
                <option value="" disabled selected>カテゴリ選択</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
            <label class="add_news_category modal_label" for="modal_chk" style="font-size:2rem; color: var(--main-color);">
                <i class="fas fa-plus-circle"></i>
            </label>
        </div>
        <textarea name="content" class="form-control" rows="10" placeholder="記事" required></textarea>
        <input type="submit" value="送信" class="original_btn original_btn_send">
    </form>
</section>

{# モーダル領域 #}
<input id="modal_chk" class="modal_chk" type="checkbox">
<div class="modal_body">
    <label class="modal_bg" for="modal_chk"></label>
    <div class="modal_content">
        <h2>カテゴリ新規追加</h2>
        <form id="news_category_form" method="POST" action="{% url 'news:add_category' %}">
            {% csrf_token %}
            <input type="text" name="name" placeholder="カテゴリ名">
            <input class="original_btn" style="padding: 0.2rem 0.5rem;" type="submit" value="登録">
            <label for="modal_chk" class="original_btn_cancel">キャンセル</label>
        </form>
        <h2 style="margin-top: 1rem;">カテゴリ一覧</h2>
        <div id="news_category_list">
            {% for category in categories %}
            <label>{{ category.name }}</label>
            {% endfor %}
        </div>
    </div>
</div>